service:
  name: serverless-test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'development'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:xxxxxxxxxxxxxx:table/usersTable" #replace with dynamo table arn

  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          method: POST
          path: users
  getUsers:
    handler: handler.getUsers
    events:
      - http:
          method: GET
          path: users
  getUser:
    handler: handler.getUser
    events:
      - http:
          method: GET
          path: users/{id}
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          method: PUT
          path: users/{id}
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          method: DELETE
          path: users/{id}

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
